## data-raw/tax_heads.R — run to rebuild data/tax_heads.rda

tax_heads <- data.frame(
  tax_head = c(
    "total_receipts",
    "income_tax",
    "capital_gains_tax",
    "inheritance_tax",
    "apprenticeship_levy",
    "nics_total",
    "nics_employer",
    "nics_employee",
    "nics_self_employed",
    "vat",
    "corporation_tax",
    "bank_levy",
    "bank_surcharge",
    "bank_payroll_tax",
    "diverted_profits_tax",
    "digital_services_tax",
    "residential_property_developer_tax",
    "energy_profits_levy",
    "electricity_generators_levy",
    "economic_crime_levy",
    "petroleum_revenue_tax",
    "fuel_duty",
    "stamp_duty_shares",
    "sdlt",
    "ated",
    "tobacco_duty",
    "spirits_duty",
    "beer_duty",
    "wine_duty",
    "cider_duty",
    "gambling_duties",
    "air_passenger_duty",
    "insurance_premium_tax",
    "landfill_tax",
    "climate_change_levy",
    "aggregates_levy",
    "soft_drinks_levy",
    "plastic_packaging_tax",
    "customs_duties",
    "miscellaneous",
    "penalties"
  ),
  description = c(
    "Total HMRC receipts",
    "Income Tax (PAYE and Self Assessment)",
    "Capital Gains Tax",
    "Inheritance Tax",
    "Apprenticeship Levy",
    "National Insurance Contributions (all classes)",
    "National Insurance Contributions - employer (Class 1 PAYE)",
    "National Insurance Contributions - employee (Class 1 PAYE)",
    "National Insurance Contributions - self-employed (Class 2 & 4)",
    "Value Added Tax",
    "Corporation Tax (onshore)",
    "Bank Levy",
    "Bank Surcharge",
    "Bank Payroll Tax",
    "Diverted Profits Tax",
    "Digital Services Tax",
    "Residential Property Developer Tax",
    "Energy Profits Levy",
    "Electricity Generators Levy",
    "Economic Crime Levy",
    "Petroleum Revenue Tax",
    "Hydrocarbon Oil Duties (Fuel Duty)",
    "Stamp Duty Reserve Tax (shares)",
    "Stamp Duty Land Tax",
    "Annual Tax on Enveloped Dwellings",
    "Tobacco Duties",
    "Spirits Duties",
    "Beer Duties",
    "Wine and Made-Wine Duties",
    "Cider and Perry Duties",
    "Betting and Gaming Duties",
    "Air Passenger Duty",
    "Insurance Premium Tax",
    "Landfill Tax",
    "Climate Change Levy",
    "Aggregates Levy",
    "Soft Drinks Industry Levy",
    "Plastic Packaging Tax",
    "Customs Duties",
    "Miscellaneous receipts",
    "Penalties and interest"
  ),
  category = c(
    "total",
    "income", "income", "income", "income",
    "nics", "nics", "nics", "nics",
    "consumption",
    "income",
    "income", "income", "income", "income", "income", "income",
    "income", "income", "income",
    "income",
    "consumption",
    "property", "property", "property",
    "consumption", "consumption", "consumption", "consumption", "consumption",
    "consumption",
    "consumption",
    "consumption",
    "environment", "environment", "environment",
    "consumption", "consumption",
    "other",
    "other", "other"
  ),
  available_from = c(
    "2016",
    "2016", "2016", "2016", "2017",
    "2016", "2016", "2016", "2016",
    "2016",
    "2016",
    "2016", "2016", "2010", "2016", "2020", "2022",
    "2022", "2023", "2023",
    "2016",
    "2016",
    "2016", "2016", "2016",
    "2016", "2016", "2016", "2016", "2016",
    "2016",
    "2016",
    "2016",
    "2016", "2016", "2016",
    "2018", "2022",
    "2016",
    "2016", "2016"
  ),
  stringsAsFactors = FALSE
)

usethis::use_data(tax_heads, overwrite = TRUE)
